backend/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :network, only: [:index] do
  end
  # resources :media,                   :defaults => { :format => :json }
  # resources :personnes,                   :defaults => { :format => :json }
  # resources :articles,                   :defaults => { :format => :json }
  # resources :sources,                   :defaults => { :format => :json }
  # resources :institutions,                   :defaults => { :format => :json }
  # resources :edges,                   :defaults => { :format => :json }
  # resources :jobs,                   :defaults => { :format => :json }
  # resources :parties,                   :defaults => { :format => :json }
  resources :personnes
end

backend/app/models/personne.rb
class Personne < ApplicationRecord
  has_many :edges
  has_many :institutions, :through => :edges
  has_many :medias, :through => :edges
  has_many :jobs, :through => :edges
  after_initialize :default_values

  def default_values
    self.selected = false
    self.selectable = true
    self.locked = false
    self.grabbable = true
    self.x = 0
    self.y = 0
    self.color = "#4c72b0"
  end
end

backend/app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render :show, status: :created, location: @personne }
      else
        format.html { render :new }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { render :show, status: :ok, location: @personne }
      else
        format.html { render :edit }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url, notice: 'Personne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.fetch(:personne, {})
    end
end

backend/app/helpers/personnes_helper.rb
module PersonnesHelper
end

backend/app/views/personnes/_form.html.erb
<%= form_with(model: personne, local: true) do |form| %>
  <% if personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% personne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/personnes/edit.html.erb
<h1>Editing Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

backend/app/views/personnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personnes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.first_name %> <%= personne.last_name %></td>
        <td><%= link_to 'Show', personne %></td>
        <td><%= link_to 'Edit', edit_personne_path(personne) %></td>
        <td><%= link_to 'Destroy', personne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personne', new_personne_path %>

backend/app/views/personnes/new.html.erb
<h1>New Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Back', personnes_path %>

backend/app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>